### PR TITLE
Armor effect tweak

### PR DESCRIPTION
**Pull request by lightningo7**
Tweak night vision length on mystic helmet

### CODE REVIEW

**Comment by sblectric** [comment]
Any particular reason you thought this change was needed?

**Comment by lightningo7** [comment]
On a modpack I've been playing I've run into an issue where the night vision is continuously trying to apply itself but it's applying weirdly and it causes a constant flickering if wearing the helmet in the nether

**Comment by sblectric** [comment]
Changing it to 25 fixes it? That's fairly interesting... if so I will add that change to the next version.

**Comment by lightningo7** [comment]
I haven't been able to test it due to the gradle voodoo not working for me but I noticed it's the only one that's different which makes me think it is

**Comment by sblectric** [comment]
I am unable to replicate this bug, but I will change the application code to only apply once a second, which should fix your issue.

**Comment by sblectric** [comment]
Also, your fix would not have worked, and would have made it worse since night vision durations under 200 ticks do the "wearing-off" flashing.

**Comment by sblectric** [comment]
Fixed in 2.7.0.

**Pull request closed without merging**
